site_name: Prestashop Beslist.nl Winkelwagen
site_description: Verbind Prestashop met uw Beslist.nl Winkelwagen account
theme: readthedocs
strict: true

pages:
  - Home: index.md
  - Configuratie:
    - 'Beslist.nl': configuratie/beslist.md
    - 'Module': configuratie/module.md
    - 'Auto import': configuratie/cron.md
  - Tests:
    - 'Orders': test/orders.md
    - 'Producten': test/producten.md
  - Gebruik:
    - 'Orders': gebruik/orders.md
    - 'Categorieën': gebruik/categorieen.md
    - 'Producten':
      - 'Producten': gebruik/producten/producten.md
      - 'Productfeed': gebruik/producten/productfeed.md
  - Integraties:
    - 'Channable': integraties/channable.md
